### ISSUE TITLE
text alignment of other languages gives a list of visemes/phonemes separate from english ones.

### ISSUE THREAD

**Issue by bluemailbox** [wuyasan/Speaking-Portal-B#113]
Each language has its own phonetic alphabet. Some are similar to english, some are nearly identical, and others are vastly different. We may need to add language support one at a time, and test if they are up to standard. our library of mouths as well are created for the english phonetic language, so this will prove a challenge to get a nice animation. Additional resources may be required, such as some extra mouths from the animator, or a way of mapping the english visemes over alternate language phonemes for a 'good enough' approach.

**Comment by wuyasan** [comment]
Tried to align Japanese text in and generate the phonemes.

**Comment by bluemailbox** [comment]
We now have a method to convert various MFA alignments in other languages to our english phonemesets and images to create animations in other languages. Additional languages will be implemented
