### ISSUE TITLE
Write script to utilize MFA input

### ISSUE THREAD

**Issue by bluemailbox** [wuyasan/Speaking-Portal-B#126]
tweaks to scheduler so we are able to import and use the .JSON file generated by the montreal forced aligner.

**Comment by yash-atreya** [comment]
Instead, convert MFA JSON to gentle's JSON structure.

**Comment by bluemailbox** [comment]
Conversion is halfway done. see jsonreorder.py

**Comment by yash-atreya** [comment]
Commit [11924e8](https://github.com/wuyasan/Speaking-Portal-B/commit/11924e893562660c80271d8d94a2436ec0038d9b) 
Conversion successful

**Comment by yash-atreya** [comment]
The only thing that remains is integrating this with the ```scheduler.py``` before video generation.

**Comment by yash-atreya** [comment]
> The only thing that remains is integrating this with the `scheduler.py` before video generation.

Could make that into a new issue (Task) after merging this

**Comment by yash-atreya** [comment]
Merged #131
